"""add test

Revision ID: 865fe0c741b8
Revises: f15119db1d2f
Create Date: 2023-08-11 23:45:52.107366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "865fe0c741b8"
down_revision: Union[str, None] = "f15119db1d2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paste", sa.Column("test", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paste", "test")
    # ### end Alembic commands ###
